default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  host: postgres
  user: postgres


development:
  <<: *default
  database: GasolinaVsAlcool_development


test:
  <<: *default
  database: GasolinaVsAlcool_test
 

production:
  <<: *default
  database: GasolinaVsAlcool_production
  username: GasolinaVsAlcool
  password: <%= ENV['GASOLINAVSALCOOL_DATABASE_PASSWORD'] %>